version: "3.9"

services:
  postgres:
    image: postgres:18.3-alpine3.22
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    networks:
      - backend

  redis:
    image: redis:8.4-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
