# Generated by Django 6.0.4 on 2026-04-26 15:27

import common.db.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(db_default=common.db.functions.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.GeneratedField(db_persist=True, expression=common.db.functions.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
            ],
            options={
                'db_table': 'merchants',
                'constraints': [models.UniqueConstraint(fields=('email',), name='merchants_email_unique')],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(db_default=common.db.functions.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20)),
                ('created_at', models.GeneratedField(db_persist=True, expression=common.db.functions.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
            options={
                'db_table': 'bank_accounts',
                'constraints': [models.UniqueConstraint(fields=('account_number',), name='bank_accounts_account_number_unique')],
            },
        ),
    ]
