# Generated by Django 6.0.4 on 2026-04-25 19:57

import merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(db_default=merchants.models.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.GeneratedField(db_persist=True, expression=merchants.models.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
    ]
