# Generated by Django 6.0.4 on 2026-04-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
    ]
