# Generated by Django 6.0.4 on 2026-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_remove_like_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(fields=('email',), name='merchants_email_unique'),
        ),
    ]
