# Generated by Django 6.0.4 on 2026-04-26 07:02

import common.db.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_merchant_email_merchant_merchants_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(db_default=common.db.functions.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20)),
                ('created_at', models.GeneratedField(db_persist=True, expression=common.db.functions.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
            options={
                'db_table': 'bank_accounts',
                'constraints': [models.UniqueConstraint(fields=('account_number',), name='bank_accounts_account_number_unique')],
            },
        ),
    ]
