# Generated by Django 6.0.4 on 2026-04-26 15:27

import common.db.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(db_default=common.db.functions.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.GeneratedField(db_persist=True, expression=common.db.functions.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchants.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchants.merchant')),
            ],
            options={
                'db_table': 'payouts',
                'indexes': [models.Index(fields=['status', 'last_attempted_at'], name='payouts_status_4adb1f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payouts_amount_paise_positive'), models.CheckConstraint(condition=models.Q(('attempts__lte', 3)), name='payouts_max_attempts')],
            },
        ),
    ]
