# Generated by Django 6.0.4 on 2026-04-26 15:27

import common.db.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(db_default=common.db.functions.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=10)),
                ('amount_paise', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.GeneratedField(db_persist=True, expression=common.db.functions.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
                ('merchant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='merchants.merchant')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payouts.payout')),
            ],
            options={
                'db_table': 'ledgers',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='ledgers_merchan_49273e_idx')],
            },
        ),
    ]
