# Generated by Django 6.0.4 on 2026-04-26 07:03

import common.db.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0004_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(db_default=common.db.functions.UUIDv7(output_field=models.UUIDField()), editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=10)),
                ('amount_paise', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.GeneratedField(db_persist=True, expression=common.db.functions.UUIDExtractTimestamp('id'), output_field=models.DateTimeField())),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledgers',
            },
        ),
    ]
