# Generated by Django 6.0.4 on 2026-04-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payouts.payout'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['merchant', 'created_at'], name='ledgers_merchan_49273e_idx'),
        ),
    ]
