# Generated by Django 6.0.4 on 2026-04-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
        ('merchants', '0004_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='merchant',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='merchants.merchant'),
        ),
    ]
