# Generated by Django 6.0.4 on 2026-04-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_ledger_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='reference_note',
        ),
    ]
