# Generated by Django 6.0.4 on 2026-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotencykey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='in_flight',
            field=models.BooleanField(default=True),
        ),
    ]
